### ISSUE TITLE
robustbench has a problem

### ISSUE THREAD

**Issue by 0001lizhubo** [xavihart/Diff-PGD#4]
```
norm_layer: list[Callable[..., nn.Module]],
TypeError: 'type' object is not subscriptable
```

**Comment by xavihart** [comment]
Can you provide more details, like which code snippet was you running and what is the detailed output of the error?

**Comment by 0001lizhubo** [comment]
I run the `attackregion.py` and `attack_physics.py`
The details:
```
Traceback (most recent call last):
  File "C:\Users\Lizhu\face_rec\Diff-PGD\code\attack_physics.py", line 7, in <module>
    from archs import get_archs
  File "C:\Users\Lizhu\face_rec\Diff-PGD\code\archs.py", line 11, in <module>
    from robustbench.utils import load_model
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\__init__.py", line 1, in <module>
    from .data import load_cifar10
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\data.py", line 15, in <module>
    from robustbench.model_zoo import model_dicts as all_models
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\model_zoo\__init__.py", line 1, in <module>
    from .models import model_dicts
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\model_zoo\models.py", line 4, in <module>
    from robustbench.model_zoo.cifar10 import cifar_10_models
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\model_zoo\cifar10.py", line 24, in <module>
    from robustbench.model_zoo.architectures.robustarch_wide_resnet import get_model as get_robustarch_model
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\model_zoo\architectures\robustarch_wide_resnet.py", line 352, in <module>
    class BottleneckTransform(nn.Sequential):
  File "C:\Users\Lizhu\miniconda3\envs\diff-pgd\lib\site-packages\robustbench\model_zoo\architectures\robustarch_wide_resnet.py", line 363, in BottleneckTransform
    norm_layer: list[Callable[..., nn.Module]],
TypeError: 'type' object is not subscriptable

```
I don't know why.

**Comment by xavihart** [comment]
An easy way is to delete the `import` related to the robustbench if u are just using other pretrained network on clean image. But I will figure it out soon.

**Comment by xavihart** [comment]
I ran the attackregion.py and it works well in my envs, please check whether you have used the updated env.yaml. Can you send me the details of your envs maybe.

**Comment by 0001lizhubo** [comment]
Ok, I know the problem what it is.
Because I use Chinese Win11 system, so when I install the robustbench v1.0, it will make mistakes as follow:
```
 pip install git+https://github.com/RobustBench/robustbench.git@v1.0

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/RobustBench/robustbench.git@v1.0
  Cloning https://github.com/RobustBench/robustbench.git (to revision v1.0) to c:\users\lizhu\appdata\local\temp\pip-req-build-26fyf8u3
  Running command git clone --filter=blob:none --quiet https://github.com/RobustBench/robustbench.git 'C:\Users\Lizhu\AppData\Local\Temp\pip-req-build-26fyf8u3'
  Running command git checkout -q d3795a05518a3086ce6035eb285a57ce4a2e5a4d
  Resolved https://github.com/RobustBench/robustbench.git to commit d3795a05518a3086ce6035eb285a57ce4a2e5a4d
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Lizhu\AppData\Local\Temp\pip-req-build-26fyf8u3\setup.py", line 4, in <module>
          long_description = fh.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 3438: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

So I have to install the robust bench v1.1. That's where the problem lies.

I will use Linux system try it again.

**Comment by xavihart** [comment]
yes, please try to use Linux
